### ISSUE TITLE
Validation at the end of every epoch.

### ISSUE THREAD

**Issue by shubhamjain0594** [torchnet/torchnet#12]
We can create two engines and do validation. But is there a better solution than this?

**Comment by jnhwkim** [comment]
`engine.hooks.onEndEpoch` may work for that senario?

**Comment by lvdmaaten** [comment]
Just added it: https://github.com/torchnet/torchnet/commit/382f579062a25f3953d95c8d586051effd91806d

We do not want to have a generic `test()` method because we want to leave the option open for people to add things like `KNNEngine`, `SVMEngine`, `DecisionTreeEngine`, etc.
