### ISSUE TITLE
Problem running the example

### ISSUE THREAD

**Issue by joeyhng** [torchnet/torchnet#16]
I may have missed something obvious, but I failed to run the provided examples. 

If I run ```th examples/mnist.lua``` torchnet directory, it gives the following error output:
```
$ th example/mnist.lua 
running on CPU	
/home/joe/torch/install/bin/luajit: /home/joe/torch/install/share/lua/5.1/threads/threads.lua:264: 
[thread 1 callback] example/mnist.lua:26: module 'mnist' not found:
	no field package.preload['mnist']
	no file [some paths in my computer]
	...
```
Where could I get the mnist dataset lua library?

**Comment by lvdmaaten** [comment]
`luarocks install mnist`
