### ISSUE TITLE
problems on the mnist example

### ISSUE THREAD

**Issue by eriche2016** [torchnet/torchnet#32]
@lvdmaaten  I donot install `mnist` dataset to my torch directory by using `luarocks install mnist` command. Rather I downloaded the [mnist](https://github.com/andresy/mnist) to a separate place `path_to_minist/`, then i try to modify the path in the example code provided by the repos. I insert the  code at https://github.com/torchnet/torchnet/blob/master/example/mnist.lua#L11  like below: 
`local mnist_pkg_path = '/home/jack/public_datasets/?/init.lua'
-- concate to package path  
package.path = mnist_pkg_path .. ';' .. package.path`  
And the leaving  remaining code of 'mnist.lua' the same.  
 however, I always get an error, donot know why? can you give me some tips? besides, other method like directly modified path of the require command in [here](https://github.com/torchnet/torchnet/blob/master/example/mnist.lua#L26), but failed.

**Comment by lvdmaaten** [comment]
Please only use the issue tracker for torchnet-related issues, not for Q&A. Just do `luarocks install mnist` and the example should work.
