### ISSUE TITLE
allocated memory estimation.

### ISSUE THREAD

**Issue by neuralix** [torchnet/torchnet#33]
How can i estimate the amount of allocated memory?

I've now used single gpu and a memory loading dataset(*.t7) file.
I met these cases. (the number of thread: 1)

case 1: dataset is 13GB, datatype is double, allocated memory: 13GB
case 2: dataset is 7GB (a half-sized one of case 1), datatype is double, allocated memory: 55GB
case 3: dataset is 13GB, datatype is float, allocated memory: 13GB
case 4: dataset is 7.7GB, datatype is float, allocated memory: 24GB

I don't know the relation. (I expected linearity.)

**Comment by lvdmaaten** [comment]
Torchnet is agnostic of GPUs, so this completely depends how you set up your code. 

Generally, you copy a batch of data to a GPU buffer in the main thread, like in https://github.com/torchnet/torchnet/blob/master/example/mnist.lua#L80-L81. In this case, the amount of GPU memory used for data is a function of your batchsize and of the dataset dimensionality.
