### ISSUE TITLE
How to shuffle selected partition after SplitDataset ?

### ISSUE THREAD

**Issue by Cadene** [torchnet/torchnet#35]
```lua
local tnt = require 'torchnet'

local d = tnt.TableDataset{data = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}}

d = d:split{
  train = 0.7,
  val   = 0.3
}

d:select('val')
print('val')
for sample in d:iterator()() do
  print(sample)
end

d:select('train')
print('train')
for sample in d:iterator()() do
  print(sample)
end

d=d:shuffle() -- gives a new dataset
print('train2')
for sample in d:iterator()() do
  print(sample)
end

d:select('val') -- no more select
print('val2')
for sample in d:iterator()() do
  print(sample)
end
```

**Comment by lvdmaaten** [comment]
Note that `d = d:shuffle()` is syntactic sugar for doing `d = tnt.ShuffleDataset{dataset = d}`. So of course `select()` is gone in `d`.

Can't you do `e = d:shuffle()` and get `sample`s from `e:iterator()`?

**Comment by Cadene** [comment]
It works now, thanks 👍 

```lua
local tnt = require 'torchnet'

local d = tnt.TableDataset{data = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}}

d = d:split{
  train = 0.7,
  val   = 0.3
}

d:select('val')
print('val')
for sample in d:iterator()() do
  print(sample)
end

d:select('train')
print('train')
for sample in d:iterator()() do
  print(sample)
end

trainset=d:shuffle()
print('train2')
for sample in trainset:iterator()() do
  print(sample)
end

d:select('val')
testset=d:shuffle()
print('val2')
for sample in testset:iterator()() do
  print(sample)
end
```

**Comment by lvdmaaten** [comment]
Be careful with this though! Your call to `d:select('val')` also changes `trainset` because `SplitDataset.select` is not actually cloning. So both `trainset` and `testset` have the same underlying dataset `d`, with the same partition `select`ed at any point in time.

We may have to consider changing `SplitDataset` to actually return a table of `Dataset`s to prevent these kinds of bugs from occurring.

**Comment by Cadene** [comment]
Oh so it doesn't solved the problem. That's what I thought in the first place. I really think returning a table of `Dataset` is a good idea.

I found this issue thinking about a possible `BootstrapDataset` which could split a dataset in two partitions :

- the first one (train) would be made with a `shuffle{remplacement=true}` call,
- the second one (val) would be made from all the non picked samples from the first partition.
