### ISSUE TITLE
Garbage Collection

### ISSUE THREAD

**Issue by karandwivedi42** [torchnet/torchnet#39]
In ParallelDatasetIterator, moving collectgarbage() from Line 109-110

https://github.com/torchnet/torchnet/blob/master/dataset/paralleldatasetiterator.lua#L109-L110

to Line 114 (i.e. in second function) 
https://github.com/karandwivedi42/torchnet/blob/mem-usage/dataset/paralleldatasetiterator.lua#L112-L113

reduces the memory usage.

Without moving, memory usage peaks at around 30GB (4 threads, 256 batchSize, fb.resnet.torch pre-processing) and after moving to second function, it peaks at around 10GB.

**Comment by lvdmaaten** [comment]
You probably want both gc calls. (Note that the `collectgarbage()` in L109-110 is running in a different thread than the the one in line 114.

Can you send a PR fixing this?
