### ISSUE TITLE
Wrapping issue when passing tables as first parameter with argcheck

### ISSUE THREAD

**Issue by gforge** [torchnet/torchnet#41]
Lua handles the brackets arguments by passing everything into the first argument as a table. There is no indicator that the function has been called using `my_function{arg1 = "hello", arg2 = "world"}` and not  with `my_function({arg1 = "hello", arg2 = "world"})`. This makes it impossible for `argcheck` to know how to parse the first argument when it is of `type = "table"` as in the [NDCGMeter](https://github.com/torchnet/torchnet/blob/master/meter/ndcgmeter.lua#L93). Here's a test case:

```lua
function test.NDCGMeter()
   local mtr = tnt.NDCGMeter{K = {6}}

   -- From: https://en.wikipedia.org/wiki/Discounted_cumulative_gain#Normalized_DCG
   local relevance = torch.DoubleTensor{3,2,3,0,1,2}
   local output = torch.linspace(relevance:size(1), 1, relevance:size(1)):double()
   mtr:add(output, relevance)

   local est = mtr:value()
   tester:eq(est[6], 0.932, "nDGC with K=6", 10^-3)
end
```

As there is only one parameter it is easy to [add a workaround][fix] (add at line 96):

```lua
         if (K.K) then
            K = K.K
         end
```

Unfortunately there is no elegant Lua solution as I see it and I've [proposed][proposal] for `argcheck` to add a table wrapper class. This allows the user to wrap the table in a class that then is easy for `argcheck` to identify. This has the downside of adding complexity but we believed that for the `torch-dataframe` [package][tdf] this was the best solution as there are plenty of instances where passing a table as the first argument makes sense.

[fix]: https://github.com/gforge/torchnet/blob/meter-tests/meter/ndcgmeter.lua#L96-L98
[proposal]: https://github.com/torch/argcheck/issues/9
[tdf]: https://github.com/AlexMili/torch-dataframe/tree/develop

**Comment by lvdmaaten** [comment]
I have had luck circumventing this issue in the past by adding `noordered = true` in the `argcheck` definition of `__init`. Does that resolve the issue for you? (And if so, can you please send a PR?)

**Comment by gforge** [comment]
Yup, the `noordered = true` solved it. I'll do a PR together with the remainder of the tests once the issue #42 with the AUC is solved.
