### ISSUE TITLE
slow and out of mem with threads on imagenet

### ISSUE THREAD

**Issue by culurciello** [torchnet/torchnet#45]
Hi guys, maybe you can suggest some help here?
https://github.com/karandwivedi42/imagenet-multiGPU.torchnet/issues/5
thanks a lot
E

**Comment by lvdmaaten** [comment]
I just commented on the thread.

**Comment by culurciello** [comment]
Hi @lvdmaaten @andresy do you guys have any insight on why this may be slow:
https://github.com/karandwivedi42/imagenet-multiGPU.torchnet/issues/4

compared to:
https://github.com/e-lab/imagenet-multiGPU.torch

batch loading and manipulations seem same...
?

**Comment by lvdmaaten** [comment]
Hard to say... it could be a lot of different things. (Also, I haven't read
both implementations in great detail.)

Are cudnn.fastest and cudnn.benchmark set to true during training? I don't
see that in the code.

**Comment by szagoruyko** [comment]
fb.resnet.torch has much heavier preprocessing, and threads cannot keep up with fast networks like AlexNet
