### ISSUE TITLE
FATAL THREAD PANIC after resuming training 

### ISSUE THREAD

**Issue by gooshan** [torchnet/torchnet#46]
For some reason ParallelDatasetIterator throws a "FATAL THREAD PANIC" error after I torch.load() (resume) a network from disk. It looks for a custom dataset class that is included in the init() and is found when simply running without resuming from a saved model. Any ideas?

**Comment by gooshan** [comment]
It turns out to be a memory issue. Unfortunately the torch error message is quite misleading as it leads one to believe that it is a dependency issue. I have slightly lowered the amount of nodes in my network and the parallel iterator works just fine.

**Comment by lvdmaaten** [comment]
Fatal thread panics usually include an error message that indicates what caused the error.
