### ISSUE TITLE
Would you provide an example for ListDataset(self, filename, load[, maxload][, path])?

### ISSUE THREAD

**Issue by neuralix** [torchnet/torchnet#47]
I'm now trying to
ParallelDatasetIterator
\+ BatchDataset
\+ ListDataset(self, filename, load[, maxload][, path])
case.

Would you provide an example for ListDataset() case using string input having filenames?

**Comment by Kaixhin** [comment]
You can find an example in [`train.lua`](https://github.com/karandwivedi42/imagenet-multiGPU.torchnet/blob/master/train.lua) of [karandwivedi42/imagenet-multiGPU.torchnet](https://github.com/karandwivedi42/imagenet-multiGPU.torchnet).

**Comment by karandwivedi42** [comment]
Actually, @neuralix I am using a t7 file instead of text file which serves the same purpose. If you specifically need text file, see @Cadene 's https://github.com/Cadene/torchnet-vision/blob/master/datasets/mit67.lua#L43-L58
