### ISSUE TITLE
Is it necessary  to shallow copy the transforms in transform.lua

### ISSUE THREAD

**Issue by eriche2016** [torchnet/torchnet#48]
I think this line is redudent [here](https://github.com/torchnet/torchnet/blob/master/transform.lua#L89), and remove this line is okay

**Comment by lvdmaaten** [comment]
I am not sure it is redundant. What if some `transform` has an upvalue the value of which is changed by the `transform` (like a buffer for intermediate results)? Then re-using a transform function in two different compositions may cause one composite transform to influence the outcome of the other (and vice versa)?

In any case: it doesn't really hurt to do a deep copy here.
