### ISSUE TITLE
Torch net install problem

### ISSUE THREAD

**Issue by changkaizhao** [torchnet/torchnet#5]
After I did:
`luarocks install torchnet`

I created a new file  "torchtest.lua" as follow:
`require ’nn’
local tnt   = require ’torchnet’
local mnist = require ’mnist’`

run 
`th torchtest.lua`

I got the errors below:
`robysmac:lua test zhaochangkai$ th torchtest.lua
/Users/zhaochangkai/torch/install/bin/luajit: .../zhaochangkai/torch/install/share/lua/5.1/trepl/init.lua:384: .../zhaochangkai/torch/install/share/lua/5.1/trepl/init.lua:384: .../zhaochangkai/torch/install/share/lua/5.1/trepl/init.lua:384: module 'tds' not found:No LuaRocks module found for tds
	no field package.preload['tds']
	no file '/Users/zhaochangkai/.luarocks/share/lua/5.1/tds.lua'
	no file '/Users/zhaochangkai/.luarocks/share/lua/5.1/tds/init.lua'
	no file '/Users/zhaochangkai/torch/install/share/lua/5.1/tds.lua'
	no file '/Users/zhaochangkai/torch/install/share/lua/5.1/tds/init.lua'
	no file './tds.lua'
	no file '/Users/zhaochangkai/torch/install/share/luajit-2.1.0-beta1/tds.lua'
	no file '/usr/local/share/lua/5.1/tds.lua'
	no file '/usr/local/share/lua/5.1/tds/init.lua'
	no file '/Users/zhaochangkai/.luarocks/lib/lua/5.1/tds.so'
	no file '/Users/zhaochangkai/torch/install/lib/lua/5.1/tds.so'
	no file './tds.so'
	no file '/usr/local/lib/lua/5.1/tds.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	.../zhaochangkai/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	torchtest.lua:2: in main chunk
	[C]: in function 'dofile'
	...gkai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x0109718d40`

I use Mac ,with cuda supported graph card.

I switched clang to version 6 in order to use cuda.
`robysmac:lua test zhaochangkai$ clang -v
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin15.4.0
Thread model: posix`

**Comment by changkaizhao** [comment]
solution:
`luarocks install tds`

**Comment by lvdmaaten** [comment]
This should be fixed by https://github.com/torchnet/torchnet/commit/132de7a53ed782a32e4c099c2a1d6333177eab83

**Comment by joeyhng** [comment]
It seems not yet fixed for ```luarocks install torchnet```. Cloning the repo and ```luarocks install rocks/torchnet-scm-1.rockspec``` works.

**Comment by lvdmaaten** [comment]
Ah, I forgot to make the same change in torch/rocks. Just sent out a PR that should fix this: https://github.com/torch/rocks/pull/120

**Comment by mehmedes** [comment]
When running `luarocks install tds`  it says:

`Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/tds-scm-1.rockspec - Failed cloning git repository.
`

**Comment by lvdmaaten** [comment]
@mehmedes I don't see anything wrong in the LuaRocks file. Do you perhaps use `git` through a proxy? Can you manually clone the TDS repo via `git clone git://github.com/torch/tds.git`?

**Comment by mehmedes** [comment]
git clone git://github.com/torch/tds.git didn't work with me. When changing to https://github.com/torch/tds.git cloning works

**Comment by lvdmaaten** [comment]
Okay so this means you have a problem with your Git setup. Perhaps you have a firewall that is blocking port 9418 (the port that the Git protocol is using)? See, for instance, [here](http://stackoverflow.com/questions/4891527/git-protocol-blocked-by-company-how-can-i-get-around-that) for possible solutions / work-arounds.

A possible work-around is to install `tds` manually: 
```
git clone https://github.com/torch/tds.git
cd tds
luarocks make rocks/tds-scm-1.rockspec
```
You may have to repeat this for other packages, too, because I presume most packages use the Git protocol. So properly fixing Git is a better solution.

**Comment by soumith** [comment]
you could run the command:
```
git config --global url.https://github.com/.insteadOf git://github.com/
```

After that `luarocks install tds` (and the other packages) might work fine.

**Comment by mehmedes** [comment]
Great! Thank you

**Comment by tylerlindell** [comment]
trying to run any of these commands on mac Sierra I get the following error

```
Undefined symbols for architecture x86_64:
  "_THAtomicSetLong", referenced from:
      _tds_atomic_set in tds_atomic_counter.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libtds.so] Error 1
make[1]: *** [CMakeFiles/tds.dir/all] Error 2
make: *** [all] Error 2
```
