### ISSUE TITLE
Main documentation not updated

### ISSUE THREAD

**Issue by karandwivedi42** [torchnet/torchnet#50]
tnt.SplitDataset treats partition values as fractions only when they are < 1, otherwise treating them as absolute partition size.

The documentation states:
`The sum of the partition weights may or may not sum to one (tnt.SplitDataset will make them sum to one!).`

This is confusing as if someone gives partitions as percentage like
`{ train = 70, test = 30 }`, the 70 and 30 are treated as absolute values rather than fraction.

Edit: Also, sum of partition weights should sum 1, or be exact size.

**Comment by karandwivedi42** [comment]
Just noticed that it is changed in internal documentation, but not in overall README.md

**Comment by lvdmaaten** [comment]
Solved by https://github.com/torchnet/torchnet/commit/d8bd1b49101c91dcddc174807e0b3cd4594a7602
