### ISSUE TITLE
putting vector as target

### ISSUE THREAD

**Issue by neuralix** [torchnet/torchnet#52]
MSE criterion needs vector(;1d tensor) type input.
But in the example codes, I could see only cases in which scalar values are put as target.
How can i take vector as target and use MSE criterion?

**Comment by lvdmaaten** [comment]
The MNIST example also uses targets stores in tensors? You can store a scalar value in a 1-tensor. So do something like `sample = {input = ..., target = torch.DoubleTensor{scalarValue}}`.
