### ISSUE TITLE
MNIST example

### ISSUE THREAD

**Issue by rave78** [torchnet/torchnet#59]
Hi,
I just want to point out a minor problem in the **mnist.lua** example related to the criterion and database iterator.

If you redefine the model and the criterion (lines 49 and 50) with the following lines, the script will fail.
```
local net = nn.Sequential():add(nn.Linear(784,10))
net:add(net:add(nn.LogSoftMax()))

local criterion = nn.ClassNLLCriterion()
```

It looks that the database iterator is returning a **target tensor** with 2D instead of 1D, which is required by ClassNLLCriterion() .  One simple solution is to reshape the sample during training 
```
engine.hooks.onSample = function(state)
    state.sample.target = state.sample.target:view(state.sample.target:nElement())
end
```

**Comment by lvdmaaten** [comment]
Yes, you are still responsible for making sure that `sample.input` and `sample.target` are appropriately sized for the model and criterion you are using.

Note that you can also use `squeeze()` to remove all dimensions with size 1 from a tensor.
