### ISSUE TITLE
Fail to require torchnet when debugging using eclipseLDT

### ISSUE THREAD

**Issue by jimxinbo** [torchnet/torchnet#61]
I am a bit new to torch. I setup eclipseLDT according to http://www.lighting-torch.com/2015/07/27/configuring-eclipse-with-torch/

I can debug code without require torchnet, but once I require torchnet, I get the following errors

qlua: .../torch/install/share/lua/5.1/argcheck/usage.lua:83: bad argument #2 to 'isatty' (FILE* expected, got table)
stack traceback:
	[C]: at 0x7f30ab2179c0
	[C]: in function 'isatty'
	.../torch/install/share/lua/5.1/argcheck/usage.lua:83: in function 'render'
	.../torch/install/share/lua/5.1/argcheck/init.lua:102: in function 'argcheck'
	.../torch/install/share/lua/5.1/torchnet/utils/table.lua:35: in main chunk
	[C]: in function 'require'
	.../torch/install/share/lua/5.1/torchnet/utils/init.lua:23: in main chunk
	[C]: in function 'require'
	.../torch/install/share/lua/5.1/torchnet/transform.lua:12: in main chunk
	[C]: in function 'require'
	...h/install/share/lua/5.1/torchnet/dataset/listdataset.lua:13: in main chunk
	[C]: in function 'require'
	.../torch/install/share/lua/5.1/torchnet/init.lua:70: in main chunk
	[C]: in function 'require'
	.../LDT_workspace/test1/src/main.lua:14: in main chunk

**Comment by lvdmaaten** [comment]
This is an issue with `argcheck`, not with `torchnet`. Please post here: https://github.com/torch/argcheck/issues

It sounds like Eclipse is overwriting `io.stdout` and/or `io.stderr` in a non-standard way.
