### ISSUE TITLE
Error using MultiLabelConfusionMeter()

### ISSUE THREAD

**Issue by uahsan3** [torchnet/torchnet#62]
Hi,

I am running the Torch demo face detector code with a different dataset - one that has 158 classes. Here is a snippet from my train.lua file. 

```
local tnt = require 'torchnet' 

local confusion = tnt.MultiLabelConfusionMeter{k = opt.numClasses}
   
       --create closure to evaluate f(X) and df/dX
       local eval_E = function(w)
       for i = 1,opt.batchSize do 
          confusion:add(y[i],yt[i])
       end
```
Etc. 

When I run the code, the error is:

> /home/uni/torch/install/bin/luajit: /home/uni/torch/install/share/lua/5.1/torch/Tensor.lua:462: Wrong size for view. Input size: 158. Output size: 1x1
stack traceback:
	[C]: in function 'error'
	/home/uni/torch/install/share/lua/5.1/torch/Tensor.lua:462: in function 'view'
	...hare/lua/5.1/torchnet/meter/multilabelconfusionmeter.lua:80: in function 'add'
	./train.lua:150: in function 'opfunc'
	/home/uni/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
	./train.lua:158: in function 'train'
	run.lua:76: in main chunk
	[C]: in function 'dofile'
	.../uni/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

Can you please help?

I looked into the code and the problem seems to be coming from the following snippet from multilabelconfusionmeter.lua:
```
if output:nDimension() == 1 then
    output = output:view(1, output:size(1))
 end
if target:nDimension() == 1 then
    target = target:view(1, output:size(1))
end
```

Since my output and target are 158-dimensional tensors, reshaping the output means output:size(1) has now changed so when target is reshaped, the error arises. 

Thank you.

**Comment by lvdmaaten** [comment]
This should now be fixed. Thanks for reporting!

**Comment by uahsan3** [comment]
@lvdmaaten Thanks!
