### ISSUE TITLE
for ListDataset, add an onComplete argument

### ISSUE THREAD

**Issue by oveddan** [torchnet/torchnet#65]
This would be useful for closing any underlying data streams for connections that were opened in order to fetch data for the list data set.

For example, let's say you want to return a `ListDataset` from a method.  This `ListDataset` loads its data from an `IndexedDataSetReader`.  When the `ListDataset` is done loading, it should be able to close the IndexedDataSetReader stream.

This would look like:

```
function getDataSet()

  local dataSetReader = tnt.IndexedDatasetReader('dataset.index', 'dataset.data');

  local someList = {1, 2, 3);

  local list = tnt.ListDataset(
    list = someList,
    load = function(idx) return dataSetReader:get(idx); end,
    ... other arguments omitted ...
    onComplete = function() dataSetReader.close() end
  )
end

**Comment by oveddan** [comment]
It looks like dataSetReader doesn't have a `close` method.  Guess this isn't necessary

**Comment by lvdmaaten** [comment]
A `Dataset` object shouldn't make assumptions about such things. You can always do this in your code:

```
local dataSetReader
local function getDataSet()

  dataSetReader = tnt.IndexedDatasetReader('dataset.index', 'dataset.data');

  local someList = {1, 2, 3);

  local list = tnt.ListDataset(
    list = someList,
    load = function(idx) return dataSetReader:get(idx); end,
    ... other arguments omitted ...
  )
end

local dataset = getDataset()

-- use dataset here ....

dataSetReader.close()
```

Alternatively, you could implement your own class that inherits from `tnt.Dataset` and implement the `__gc` function (which is called when the object gets garbage-collected) to close open files.
