### ISSUE TITLE
How can i use MSE criterion?

### ISSUE THREAD

**Issue by neuralix** [torchnet/torchnet#71]
Running examples/mnist.lua simply, i can't change criterion to MSE Criterion.
Can you tell me the how-to?

**Comment by lvdmaaten** [comment]
Sorry but this is for reporting issues in torch*net*, not for general Torch questions.

https://github.com/torch/nn/blob/master/doc/criterion.md#msecriterion

**Comment by neuralix** [comment]
Are you convince it?

**Comment by neuralix** [comment]
i was the guy who asked. but i think the problem is still exist.

**Comment by Kaixhin** [comment]
Yes, you cannot just use any criterion. The MNIST example is for classification, whereas MSE should be used for regression. This can be found in the [Torch nn documentation](https://github.com/torch/nn/blob/master/doc/criterion.md#criterions).

**Comment by neuralix** [comment]
Thank you.

**Comment by neuralix** [comment]
I suspect returning vector in getIterator(mode) {...} is not work.

target = torch.LongTensor(1,10) or target = torch.LongTensor(10, 1)
(instead of original line,
target = torch.LongTensor{dataset.label[idx] + 1}  )
make error.

Will you have a plan to enhance it near some day?
