### ISSUE TITLE
IndexedDataset using string as index for large dataset

### ISSUE THREAD

**Issue by Cadene** [torchnet/torchnet#72]
Hi !

I would like to extract features from a large dataset of images and to store them in memory.
IndexedDataset provides a really nice way to handle large dataset, however indexes must be integer:
`first_tensor = dataset:get(1)`

For now, I am using a tds.Hash to store the image names as keys and the corresponding indexes as values. Thus I am doing:
`first_tensor = dataset:get(tdshash[first_image_name])`

Do you know a better way to handle this using torchnet ?

Thank you for your precious help.

Greetings,
Remi

**Comment by lvdmaaten** [comment]
This sounds like a sensible approach to me. What is the problem with it?

**Comment by Cadene** [comment]
Actually, I could not make up my mind between using tds.Hash or torch-hdf5 for the hash table or looking for something else in torchnet.

tds.Hash seems to be perfect for a not so large dataset (mscoco size).

Thanks for your help.

**Comment by lvdmaaten** [comment]
Well when you're training with SGD, you wouldn't need the tds.Hash() at all. I would expect you only use it when you want to compute results for specific images at test time.

**Comment by Cadene** [comment]
You are right. However, my dataset is multimodal (Visual Question Answering). Thus I need to extract in a first time the features associated to the mscoco images. Then I train my model with SGD  over the VQA annotations datasets. Two annotations can be associated to the same mscoco image.
That is why I need such a nested pipeline.
