### ISSUE TITLE
This error is unclear - what is the problem with my code that is causing this?

### ISSUE THREAD

**Issue by pratheeksh** [torchnet/torchnet#74]
qlua: ...hare/lua/5.1/torchnet/meter/multilabelconfusionmeter.lua:107: attempt to index local 'pos' (a nil value)
stack traceback:
	[C]: in function '__index'
	...hare/lua/5.1/torchnet/meter/multilabelconfusionmeter.lua:107: in function 'add'
	main.lua:198: in function 'hooks'
	...ch/install/share/lua/5.1/torchnet/engine/optimengine.lua:105: in function 'train'
	main.lua:218: in main chunk

**Comment by lvdmaaten** [comment]
Are you sure you have the latest version of torchnet installed? There is no indexing of `pos` in line 107 (there is one in line 108): https://github.com/torchnet/torchnet/blob/master/meter/multilabelconfusionmeter.lua#L107

If you confirmed an your version of `multilabelconfusionmeter.lua` is identical to the one on Github but still see the error, can you please post a repro for this issue?

**Comment by pratheeksh** [comment]
I just reinstalled torchnet and compared files and I have the exact same file, but the error persists. I think pos is null for some reason so, pos:nElement() is bugging out. I do not understand what exactly posting a repro means. Let me know if you need anything else. Thank you for responding!

**Comment by lvdmaaten** [comment]
Can you post a small code example of how you use `MultilabelConfusionMeter` that reproduces the error you are seeing?
