### ISSUE TITLE
meter.MultilabelConfusionMeter invalid argument error

### ISSUE THREAD

**Issue by sunwooOh** [torchnet/torchnet#80]
Hi.
I tried to use the MultilabelConfusionMeter with following code:
```
	local tnt = require 'torchnet'
	meter = tnt.MultiLabelConfusionMeter(#classes, false)
```
and got error messege:

>    +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
>    tnt.MultiLabelConfusionMeter(self, k[, normalized])
> 
>     {
>        self       = tnt.MultiLabelConfusionMeter  -- 
>        k          = number                        -- 
>       [normalized = boolean]                      --  [default=true]
>     }
>     
> 
>     The tnt.MultiLabelConfusionMeter constructs a confusion matrix for multi-
>     label, multi-class classification problems. In constructing the confusion
>     matrix, the number of positive predictions is assumed to be equal to the
>     number of positive labels in the ground-truth. Correct predictions (that
>     is, labels in the prediction set that are also in the ground-truth set) are
>     added to the diagonal of the confusion matrix. Incorrect predictions (that
>     is, labels in the prediction set that are not in the ground-truth set) are
>     equally divided over all non-predicted labels in the ground-truth set.
> 
>     At initialization time, the k parameter that indicates the number of
>     classes in the classification problem under consideration must be
>     specified. Additionally, an optional parameter normalized (default = false)
>     may be specified that determines whether or not the confusion matrix is
>     normalized (that is, it contains percentages) or not (that is, it contains
>     counts).
> 
>     The add(output, target) method takes as input an NxK tensor output that
>     contains the output scores obtained from the model for N examples and K
>     classes, and a corresponding NxK-tensor target that provides the targets
>     for the N examples using one-hot vectors (that is, vectors that contain
>     only zeros and a single one at the location of the target value to be
>     encoded).
> 
>     The value() method has no parameters and returns the confusion matrix in a
>     KxK tensor. In the confusion matrix, rows correspond to ground-truth
>     targets and columns correspond to predicted targets.
> 
>     Got: tnt.MultiLabelConfusionMeter, number, boolean
> invalid arguments!

It looks like tnt.MultiLabelConfusionMeter, number boolean is passed, as it should.
But then why do I see this messege?

Sunwoo

**Comment by lvdmaaten** [comment]
Thanks for reporting; I will send out a fix soon. 

In the meantime, you can do:
```
meter = tnt.MultiLabelConfusionMeter{k = #classes, normalized = false}
```
