### ISSUE TITLE
bug in transform.tablemergekeys()

### ISSUE THREAD

**Issue by ZongweiZhou1** [torchnet/torchnet#82]
the transform.tablemergekey() provides a simple example:
```lua
x = { sample1 = {input = 1, target = "a"} , sample2 = {input = 2, target = "b", flag = "hard"}}
transform.tablemergekeys(x)
````
but some errors are thrown out.

it's all right when I replace 'x' by ' x = { {input = 1, target = "a"} , {input = 2, target = "b", flag = "hard"}}'.
I think the 'ipairs' in line 243 of 'transform.lua' should be fixed as 'pairs'

**Comment by lvdmaaten** [comment]
Good catch!

I am scared of changing line 243 from `ipairs` to `pairs`, as `pairs` does not give a guarantee on the order in which keys are processed. I think torchnet uses array-style tables nearly everywhere, and so is making implicit assumptions that the order of examples is maintained between transforms.

I think it is better to change the documentation instead to clarify that samples are typically not "keyed".

**Comment by lvdmaaten** [comment]
Good catch, will fix this!
