### ISSUE TITLE
Hi, I doubt that whether I can use torchnet in win10 64x. Could anybody tell me?

### ISSUE THREAD

**Issue by liangbh6** [torchnet/torchnet#86]

**Comment by liujunchangqq** [comment]
is the torchnet can only be used in linux? when I import torchnet, this error came out: ImportError: DLL load failed: 找不到指定的模块。

**Comment by lvdmaaten** [comment]
Did the error not say _which_ module could not be loaded?

Torchnet itself contains only Lua code, so it should work on Windows provided that you have a working Lua installation. 

Having said that, it is possible that one or more of torchnet's dependencies do not have Windows support. The list of dependencies is here: https://github.com/torchnet/torchnet/blob/master/rocks/torchnet-scm-1.rockspec#L18-L26
My guess is it is quite likely the `threads` package may not have Windows support but I'm not 100% sure.

Please open an issue on the Github of the dependency that is causing the issue.
