### ISSUE TITLE
How to add torchnet to a custom package on kaggle

### ISSUE THREAD

**Issue by gxyzdzj** [torchnet/torchnet#88]
How to add torchnet to a custom package on kaggle
![3](https://user-images.githubusercontent.com/40283609/41529566-2e248a3c-7320-11e8-9af6-c8a62afebf80.jpg)

**Comment by lvdmaaten** [comment]
I'm afraid this is not possible because of limitations in Kaggle. Kaggle supports Python (pip) and R (CRAN) packages, but not Lua (luarocks) packages.
