### ISSUE TITLE
Transforms

### ISSUE THREAD

**Issue by gooshan** [torchnet/torchnet#9]
Recently I found a very nice set of preprocessing transformations in a [project](https://www.google.bg/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjEntfPgcvNAhUHOxQKHVt_DmMQFggcMAA&url=https%3A%2F%2Fgithub.com%2Ffacebook%2Ffb.resnet.torch&usg=AFQjCNFkLdNbFostXKJUC0qkSLbOVXdeWA&sig2=AMZJOyQ8iC1XEL_igpWjjg) by Facebook implementing ResNet (of which you are probably aware). I guess adapting and incorporating [transforms.lua](https://github.com/facebook/fb.resnet.torch/blob/master/datasets/transforms.lua) will be a nice addition to torchnet.

**Comment by lvdmaaten** [comment]
We are aware of this code (Torchnet was initiated at Facebook, also). 

The idea of Torchnet is to develop separate subpackages that implement functionality to specific domains. These functions are specific to vision, so it would make sense to include them in `torchnet-vision` subpackage in the `torchnet` org. Similarly, we would like to develop packages like `torchnet-speech` and `torchnet-nlp` (exact names to be determined).

**Comment by gooshan** [comment]
I see. Amazing work so far, thank you!

**Comment by Cadene** [comment]
@gooshan I made a repo [torchnet-vision](https://github.com/Cadene/torchnet-vision) where I incorporated transforms.lua in a torchnet fashion.

**Comment by gooshan** [comment]
@Cadene  thanks, nicely done. @lvdmaaten I too would be happy to contribute to a broader tochnet-vision project (e.g.: specific dataset loaders)

**Comment by Cadene** [comment]
@gooshan I just added a roadmap to the [readme](https://github.com/Cadene/torchnet-vision/blob/master/README.md). Feel free to contribute :) I am currently playing with torchnet to see what functionalities could be added to torchnet-vision.
